CREATE TABLE IF NOT EXISTS Project (
    ID CHAR(256) PRIMARY KEY NOT NULL,
    Description TEXT NOT NULL,
    DataTime VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS Analyzer (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ProjectID CHAR(256) NOT NULL,
    Content TEXT NOT NULL,
    Cfg TEXT NULL,
    CONSTRAINT fk_project
        FOREIGN KEY(ProjectID) 
        REFERENCES Project(ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Input (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ProjectID CHAR(256) NOT NULL,
    Content TEXT NOT NULL,
    Source TEXT NOT NULL,
    PluginName CHAR(256) NULL,
    PluginMethod CHAR(256) NULL,
    Plugin TEXT NULL,
    CONSTRAINT fk_project
        FOREIGN KEY(ProjectID) 
        REFERENCES Project(ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Output (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ProjectID CHAR(256) NOT NULL,
    Content TEXT,
    Cfg TEXT NULL,
    CONSTRAINT fk_project
        FOREIGN KEY(ProjectID) 
        REFERENCES Project(ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Translator (
    Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ProjectID CHAR(64) NOT NULL,
    L1 TEXT,
    L2 TEXT,
    REJECTED TEXT,
    VOCABULARY TEXT,
    Cfg TEXT NULL,
    CONSTRAINT fk_project
        FOREIGN KEY(ProjectID) 
        REFERENCES Project(ID)
        ON DELETE CASCADE
);
